### ISSUE TITLE
Uploads not opening in FancyBox

### ISSUE THREAD

**Issue by tomheaps** [formtools/core#115]
In the latest build  of formtools 3 alpha, there is an error when you set uploaded files to open via fancybox - when you click on the file link to open it gets stuck on the loading spinner and the following error message appears in the console:

> Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Nodes of type '#document' may not be inserted inside nodes of type '#document-fragment'.
>     at Function.clean (/global/scripts/jquery.js:16:60844)
>     at Function.d.buildFragment (/global/scripts/jquery.js:16:58957)
>     at init.domManip (/global/scripts/jquery.js:16:58387)
>     at init.append (/global/scripts/jquery.js:16:55782)
>     at init.html (/global/scripts/jquery.js:16:57313)
>     at Object.success (/global/fancybox/jquery.fancybox-1.3.4.pack.js:24:118)
>     at Object.resolveWith (/global/scripts/jquery.js:16:13123)
>     at v (/global/scripts/jquery.js:16:67619)
>     at XMLHttpRequest.c (/global/scripts/jquery.js:16:73266)

**Comment by tomheaps** [comment]
Realized that fancy box only works with images, iframes, SWF movies and html elements - not other documents!
