### ISSUE TITLE
Upgrading formtools to 3.0

### ISSUE THREAD

**Issue by sfaro1** [formtools/core#174]
Hi all

before he upgrade i had the 2.2x version but after upgrading i keep getting 500 error when trying to visit the formtools directory / site 

after checking the formtools error log i saw this 

thrown in /home/easytrackxadmin/public_html/formtools/global/code/hooks.php on line 121
[03-Apr-2018 02:10:22 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /home/easytrackxadmin/public_html/formtools/global/code/hooks.php:121
Stack trace:
#0 /home/easytrackxadmin/public_html/formtools/global/code/hooks.php(190): ft_get_hook_calls('start', 'code', 'ft_db_connect')
#1 /home/easytrackxadmin/public_html/formtools/global/code/general.php(31): ft_process_hook_calls('start', Array, Array)
#2 /home/easytrackxadmin/public_html/formtools/global/init_page.php(16): ft_db_connect()
#3 /home/easytrackxadmin/public_html/formtools/global/session_start.php(19): require_once('/home/easytrack...')
#4 /home/easytrackxadmin/public_html/formtools/index.php(3): require_once('/home/easytrack...')
#5 {main}

can you pls help me ?

**Comment by benkeen** [comment]
Hi @sfaro1, sorry for not getting back to you sooner, I've been out of town the last few days. 

It sounds like maybe the upgrade files weren't all fully uploaded to your server. The error is complaining about Form Tools 2.x files and errors - all those files it mentioned no longer exist in the new version. Could you try re-uploading all the files?
