### ISSUE TITLE
Cannot create email templates

### ISSUE THREAD

**Issue by jivy59** [formtools/core#221]
Everything has been fine, but today I am not able to save email templates. When I attempt to save a template I get a blank screen after pressing the update button.  

Changed from Firefox to Chrome and it shows a 500 error.  Possible that file or directory permissions have changed?  What are the recommended permissions for formtools?  Any thing else to check?

System check module shows no errors or problems.

**Comment by jivy59** [comment]
Running Formtools 3.0.1  
The problem occurs when form tools tries to access this url: http://mydomain.com/formtools/admin/forms/edit/index.php?page=edit_email
That page comes up blank.  If I look at the source, there is only one blank line.
If I navigate to "../formtools/admin/forms/edit" there is an error log conting these lines:
====================
[18-May-2018 00:29:18 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[01000]: Warning: 1265 Data truncated for column 'email_reply_to' at row 1' in /home/wlrwogof/public_html/formtools/global/code/Database.class.php:143
Stack trace:
#0 /home/wlrwogof/public_html/formtools/global/code/Database.class.php(143): PDOStatement->execute()
#1 /home/wlrwogof/public_html/formtools/global/code/Emails.class.php(967): FormTools\Database->execute()
#2 /home/wlrwogof/public_html/formtools/admin/forms/edit/page_edit_email.php(20): FormTools\Emails::updateEmailTemplate('49', Array)
#3 /home/wlrwogof/public_html/formtools/admin/forms/edit/index.php(122): require_once('/home/wlrwogof/...')
#4 {main}
  thrown in /home/wlrwogof/public_html/formtools/global/code/Database.class.php on line 143
[18-May-2018 00:47:23 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[01000]: Warning: 1265 Data truncated for column 'email_reply_to' at row 1' in /home/wlrwogof/public_html/formtools/global/code/Database.class.php:143
Stack trace:
#0 /home/wlrwogof/public_html/formtools/global/code/Database.class.php(143): PDOStatement->execute()
#1 /home/wlrwogof/public_html/formtools/global/code/Emails.class.php(967): FormTools\Database->execute()
#2 /home/wlrwogof/public_html/formtools/admin/forms/edit/page_edit_email.php(20): FormTools\Emails::updateEmailTemplate('50', Array)
#3 /home/wlrwogof/public_html/formtools/admin/forms/edit/index.php(122): require_once('/home/wlrwogof/...')
#4 {main}
  thrown in /home/wlrwogof/public_html/formtools/global/code/Database.class.php on line 143

===========================
