### ISSUE TITLE
Problem after install Openssl: 

### ISSUE THREAD

**Issue by dropej** [formtools/core#384]
PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in /var/www/html/phpmood/formtools/global/code/Database.class.php:71
Stack trace:
#0 /var/www/html/phpmood/formtools/global/code/Settings.class.php(84): FormTools\Database->query('\n              ...')
#1 /var/www/html/phpmood/formtools/global/code/User.class.php(50): FormTools\Settings::get(Array)
#2 /var/www/html/phpmood/formtools/global/code/Core.class.php(816): FormTools\User->__construct()
#3 /var/www/html/phpmood/formtools/global/code/Core.class.php(388): FormTools\Core::initUser()
#4 /var/www/html/phpmood/formtools/index.php(15): FormTools\Core::init()
#5 {main}
  thrown in /var/www/html/phpmood/formtools/global/code/Database.class.php on line 71

**Comment by benkeen** [comment]
Hi @dropej, funny... I just ran into this same issue tonight on another chap's installation. 

Where do you see the error? On one of your forms that uses the Form Tools API? 

Total stab in the dark, but you might want to try editing the `global/code/Core.class.php` file and look for the loadConfigFile method. The first 3 lines of that look like this:

```php
if (self::checkConfigFileExists()) {
	require_once(self::getConfigFilePath());
}
```

Try changing `require_once` to `require`.

**Comment by dropej** [comment]
I change require_once to require and do not resolve the problem.

**Comment by sf23103** [comment]
@dropej - Just a quick suggestion, did you edit the config.php file and add change http to https for $g_root_url?

**Comment by benkeen** [comment]
Hey @sf23103, yeah I strongly suspect it's a setting. @dropej and I just emailed but his server is failing on a Settings DB query when the page loads, but it's not providing any details about the nature of the error, so it's time to check the PHP error logs... 

Curiously, in this instance I'm not even able to `catch () {}` the error, so there'd be no way to ward against this problem on this server (e.g. show a nice "Houston, we have a problem" error message).
