### ISSUE TITLE
http Error 500 after upgrade 3.0.3 to 3.0.11 (latest)

### ISSUE THREAD

**Issue by neijek** [formtools/core#458]
Did the upgrade procedure, logged in., clicked update, made the zip logged out, and uploaded (as i've done many times in the last) and as i try to visit the site again error http 500 (both in admin page or a form page).

This is the error log:

`[24-Jan-2019 10:10:11 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_enabled' in 'field list' in /home/effectiv/public_html/formtools/global/code/Database.class.php:71
Stack trace:
#0 /home/effectiv/public_html/formtools/global/code/Database.class.php(71): PDO->prepare('\n            UP...')
#1 /home/effectiv/public_html/formtools/global/code/FieldTypes.class.php(1809): FormTools\Database->query('\n            UP...')
#2 /home/effectiv/public_html/formtools/global/code/FieldTypes.class.php(1768): FormTools\FieldTypes::resetFieldTypeByIdentifier('checkboxes')
#3 /home/effectiv/public_html/formtools/global/code/Upgrade.class.php(38): FormTools\FieldTypes::resetFieldTypes()
#4 /home/effectiv/public_html/formtools/index.php(18): FormTools\Upgrade::upgrade()
#5 {main}
  thrown in /home/effectiv/public_html/formtools/global/code/Database.class.php on line 71
[24-Jan-2019 10:10:22 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_enabled' in 'field list' in /home/effectiv/public_html/formtools/global/code/Database.class.php:71
Stack trace:
#0 /home/effectiv/public_html/formtools/global/code/Database.class.php(71): PDO->prepare('\n            UP...')
#1 /home/effectiv/public_html/formtools/global/code/FieldTypes.class.php(1809): FormTools\Database->query('\n            UP...')
#2 /home/effectiv/public_html/formtools/global/code/FieldTypes.class.php(1768): FormTools\FieldTypes::resetFieldTypeByIdentifier('checkboxes')
#3 /home/effectiv/public_html/formtools/global/code/Upgrade.class.php(38): FormTools\FieldTypes::resetFieldTypes()
#4 /home/effectiv/public_html/formtools/index.php(18): FormTools\Upgrade::upgrade()
#5 {main}
  thrown in /home/effectiv/public_html/formtools/global/code/Database.class.php on line 71`

**Comment by neijek** [comment]
btw everything was working perfectly before uploading the upgrade zip and overwriting everything,. 

thanks for any and all help :)

**Comment by benkeen** [comment]
Hmm, thanks @neijek - I'll take a look tonight. That `is_enabled` field was recently added to the modules table, but the upgrade script should have added it. I'll keep you posted.

**Comment by benkeen** [comment]
Drat, confirmed. I'll release 3.0.12 out tonight to fix this problem, apologies. What happened is actually a curious logical loophole which I didn't spot: the upgrade script runs through a sequence of updates to get your installation up to date, upgrading whatever DB changes are needed for each version that's been released since your version. But with 3.0.10, I altered the field types table to add that new field - so an earlier versions update method is failing, causing the error you spotted (Thanks for the error logs, btw! Really helped).

When testing the 3.0.10 update, I didn't try upgrading from a version earlier than 3.0.5, so never saw the error.

Anyway, update coming shortly!

**Comment by benkeen** [comment]
@neijek, since you won't be able to generate a fresh upgrade bundle, just do this:

- download the latest zipfile from here: https://formtools.org/download/
- unzip it locally
- copy the `global/code/Core.class.php` and `global/code/Upgrade.class.php` files from the new zipfile and overwrite those files in your installation. 

Then go to your Form Tools login page again. It should then work properly and say you've been upgraded to 3.0.12. Let me know if you have any problems!

**Comment by neijek** [comment]
ill test today and let you all know, btw just wish to commend the speed of your replies and effort wheres the donate button i want to buy you a beer. 

Thanks. be back as soon as I test.

**Comment by neijek** [comment]
ALRIGHT, that did it, back up and running (forms works and so does admin back end). ! thanks 

One quick odd thing thought, it does still say "update" next to the 3.0.12 version top right.

the update link generates this: 

https://formtools.org/upgrade/?m=3.0.12&rt=main&rd=20190124&api=2.0.0&t1=classicgrey&tv1=2.0.5&t2=default&tv2=1.0.0&m1=data_visualization&mv1=2.1.0&m2=export_manager&mv2=3.0.5&m3=field_type_file&mv3=2.1.1&m4=form_builder&mv4=2.0.10&m5=pages&mv5=2.0.6&m6=swift_mailer&mv6=2.0.6&m7=system_check&mv7=2.1.4&m8=field_type_tinymce&mv8=2.0.7

and on the site it says:

> CoreForm Tools Core (includes default theme) 3.0.12 No newer version
> All components are up to date!

so i figure it's just something odd as we did a partial update via just those two files you had me send up. but figure id report it :) 

thanks man

**Comment by benkeen** [comment]
No problem, sorry for the fuss! 

And yeah, don't worry, the `Update` link should always be there: your individual FT installation doesn't know if's up to date or not until it sends the contents to the FT site.
