### ISSUE TITLE
Swiftmailer table field missing

### ISSUE THREAD

**Issue by ocbroadband** [formtools/core#639]
Hi Ben,

Not sure how this happened, but it appears one of the table fields has gone missing.  Here is the error I get when doing a system check on the tables...

Swift Mailer - missing table: ft3_module_swift_mailer_email_template_fields

I'm not quite sure how it disappeared, but I'm not sure what would be the easiest way to resolve it.  As of right now, I am not receiving emails for new forms submitted.

Thanks,

Lyle

**Comment by ocbroadband** [comment]
Some additional Error log information when attempting to uninstall the swiftmailer...

>[23-Oct-2019 16:09:25 America/Los_Angeles] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'xxx.ft3_module_swift_mailer_email_template_fields' in /home/xxx/xxx/ft/global/code/Database.class.php:157
Stack trace:
#0 /home/xxx/xxx/ft/global/code/Database.class.php(157): PDOStatement->execute()
#1 /home/xxx/xxx/ft/modules/swift_mailer/code/Module.class.php(132): FormTools\Database->execute()
#2 /home/xxx/xxx/ft/global/code/Modules.class.php(585): FormTools\Modules\SwiftMailer\Module->uninstall('7')
#3 /home/xxx/xxx/ft/admin/modules/index.php(27): FormTools\Modules::uninstallModule('7')
#4 {main}
  thrown in /home/xxx/xxx/ft/global/code/Database.class.php on line 157

**Comment by benkeen** [comment]
Boy, you're having a go of it today! 

Yes, the script probably assumes the table is there when uninstalling so throws an error as well. But I took a look at the module and the hooks don't look right, so don't bother trying to reinstall right now. 

I'm really tight for time but give me a few days and I'll release an update to the module to clean up a couple of things:
- better error handling on the uninstallation if the table was accidentally removed,
- re-examine the hooks. From what I can see hooks look incorrect, meaning that proper integration with Form Tools won't work. I could be mistaken, but that's what it looks like right now.

**Comment by ocbroadband** [comment]
Ben,

So as a last resort, I was able to just recreate this table from a backup sql save I had.  Looks like it was fairly straight forward and doesn't have much information in it other than the following.

>CREATE TABLE `ft3_module_swift_mailer_email_template_fields` (
  `email_template_id` mediumint(9) NOT NULL,
  `return_path` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO `ft3_module_swift_mailer_email_template_fields` (`email_template_id`, `return_path`) VALUES
(1, ''),
(2, ''),
(3, '');
ALTER TABLE `ft3_module_swift_mailer_email_template_fields`
  ADD PRIMARY KEY (`email_template_id`);
COMMIT;

I ended up doing about 3-4 test submissions, and it appears that the 'timeout' issue I was experiencing has vanished, so that's a good thing.  I'm now receiving the emails as well.   So I guess this was a bad/good thing.  Bad it broke, but good it's resolved and found a bug for you to fix.  :)
