### ISSUE TITLE
Uncaught PDOException: SQLSTATE[HY000]: General error: 1835

### ISSUE THREAD

**Issue by flcowboy7** [formtools/core#749]
Error messages received today. Directory paths changed below to obfuscate the host website.

.
**When attempting to reach the FormTools login page on the host website:**
```
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1835 Malformed communication packet in /formtools/global/code/Database.class.php:157

Stack trace:
#0 /formtools/global/code/Database.class.php(157): PDOStatement->execute()
#1 /formtools/global/code/Settings.class.php(72): FormTools\Database->execute()
#2 /formtools/global/code/Upgrade.class.php(13): FormTools\Settings::get('program_version')
#3 /formtools/index.php(23): FormTools\Upgrade::upgrade()
#4 {main} thrown in /formtools/global/code/Database.class.php on line 157
```

.
**When attempting to submit a form on the host website:**
```
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1835 Malformed communication packet in /formtools/global/code/Database.class.php:157

Stack trace:
#0 /formtools/global/code/Database.class.php(157): PDOStatement->execute()
#1 /formtools/global/code/Settings.class.php(55): FormTools\Database->execute()
#2 /formtools/global/code/General.class.php(1252): FormTools\Settings::get()
#3 /formtools/global/code/Emails.class.php(426): FormTools\General::getSubmissionPlaceholders(43, '9098', 'email_template')
#4 /formtools/global/code/Emails.class.php(1285): FormTools\Emails::getEmailComponents(43, '9098', 81)
#5 /formtools/global/code/Emails.class.php(1270): FormTools\Emails::processEmailTemplate(43, '9098', 81)
#6 /formtools/global/api/API.class.php(752): FormTools\Emails::sendEmails('on_submission', 43, '909 in /formtools/global/code/Database.class.php on line 157
```

**Comment by flcowboy7** [comment]
It looks like this was a direct result of the MariaDB v10.3.26 update last night. Our web host was able to revert back to MariaDB v10.3.25 (which allowed forms to work again) and impede further update attempts, temporarily, at least until this can be patched.
