### ISSUE TITLE
php fatal error Uncaught Error: Call to undefined function mysql_query()

### ISSUE THREAD

**Issue by resetjet** [formtools/core#776]
Our webform stopped relaying requests.  I looked at the error log and this is what I got.  Any ideas?  thanks

[15-Mar-2021 18:46:04 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /home/timberli/public_html/ftools/global/code/hooks.php:121
Stack trace:
#0 /home/timberli/public_html/ftools/global/code/hooks.php(190): ft_get_hook_calls('start', 'code', 'ft_db_connect')
#1 /home/timberli/public_html/ftools/global/code/general.php(31): ft_process_hook_calls('start', Array, Array)
#2 /home/timberli/public_html/ftools/global/library.php(379): ft_db_connect()
#3 /home/timberli/public_html/ftools/process.php(20): require_once('/home/timberli/...')
#4 {main}
  thrown in /home/timberli/public_html/ftools/global/code/hooks.php on line 121
[15-Mar-2021 22:15:31 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /home/timberli/public_html/ftools/global/code/hooks.php:121
Stack trace:
#0 /home/timberli/public_html/ftools/global/code/hooks.php(190): ft_get_hook_calls('start', 'code', 'ft_db_connect')
#1 /home/timberli/public_html/ftools/global/code/general.php(31): ft_process_hook_calls('start', Array, Array)
#2 /home/timberli/public_html/ftools/global/library.php(379): ft_db_connect()
#3 /home/timberli/public_html/ftools/process.php(20): require_once('/home/timberli/...')
#4 {main}
  thrown in /home/timberli/public_html/ftools/global/code/hooks.php on line 121
[16-Mar-2021 00:52:37 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /home/timberli/public_html/ftools/global/code/hooks.php:121
Stack trace:
#0 /home/timberli/public_html/ftools/global/code/hooks.php(190): ft_get_hook_calls('start', 'code', 'ft_db_connect')
#1 /home/timberli/public_html/ftools/global/code/general.php(31): ft_process_hook_calls('start', Array, Array)
#2 /home/timberli/public_html/ftools/global/library.php(379): ft_db_connect()
#3 /home/timberli/public_html/ftools/process.php(20): require_once('/home/timberli/...')
#4 {main}
  thrown in /home/timberli/public_html/ftools/global/code/hooks.php on line 121
[16-Mar-2021 15:47:51 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /home/timberli/public_html/ftools/global/code/hooks.php:121
Stack trace:
#0 /home/timberli/public_html/ftools/global/code/hooks.php(190): ft_get_hook_calls('start', 'code', 'ft_db_connect')
#1 /home/timberli/public_html/ftools/global/code/general.php(31): ft_process_hook_calls('start', Array, Array)
#2 /home/timberli/public_html/ftools/global/library.php(379): ft_db_connect()
#3 /home/timberli/public_html/ftools/process.php(20): require_once('/home/timberli/...')
#4 {main}
  thrown in /home/timberli/public_html/ftools/global/code/hooks.php on line 121
[16-Mar-2021 15:52:39 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /home/timberli/public_html/ftools/global/code/hooks.php:121
Stack trace:
#0 /home/timberli/public_html/ftools/global/code/hooks.php(190): ft_get_hook_calls('start', 'code', 'ft_db_connect')
#1 /home/timberli/public_html/ftools/global/code/general.php(31): ft_process_hook_calls('start', Array, Array)
#2 /home/timberli/public_html/ftools/global/library.php(379): ft_db_connect()
#3 /home/timberli/public_html/ftools/process.php(20): require_once('/home/timberli/...')
#4 {main}
  thrown in /home/timberli/public_html/ftools/global/code/hooks.php on line 121
[16-Mar-2021 17:08:19 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /home/timberli/public_html/ftools/global/code/hooks.php:121
Stack trace:
#0 /home/timberli/public_html/ftools/global/code/hooks.php(190): ft_get_hook_calls('start', 'code', 'ft_db_connect')
#1 /home/timberli/public_html/ftools/global/code/general.php(31): ft_process_hook_calls('start', Array, Array)
#2 /home/timberli/public_html/ftools/global/library.php(379): ft_db_connect()
#3 /home/timberli/public_html/ftools/process.php(20): require_once('/home/timberli/...')
#4 {main}
  thrown in /home/timberli/public_html/ftools/global/code/hooks.php on line 121
[16-Mar-2021 17:49:08 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /home/timberli/public_html/ftools/global/code/hooks.php:121
Stack trace:
#0 /home/timberli/public_html/ftools/global/code/hooks.php(190): ft_get_hook_calls('start', 'code', 'ft_db_connect')
#1 /home/timberli/public_html/ftools/global/code/general.php(31): ft_process_hook_calls('start', Array, Array)
#2 /home/timberli/public_html/ftools/global/library.php(379): ft_db_connect()
#3 /home/timberli/public_html/ftools/process.php(20): require_once('/home/timberli/...')
#4 {main}
  thrown in /home/timberli/public_html/ftools/global/code/hooks.php on line 121
[16-Mar-2021 17:50:37 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /home/timberli/public_html/ftools/global/code/hooks.php:121
Stack trace:
#0 /home/timberli/public_html/ftools/global/code/hooks.php(190): ft_get_hook_calls('start', 'code', 'ft_db_connect')
#1 /home/timberli/public_html/ftools/global/code/general.php(31): ft_process_hook_calls('start', Array, Array)
#2 /home/timberli/public_html/ftools/global/library.php(379): ft_db_connect()
#3 /home/timberli/public_html/ftools/process.php(20): require_once('/home/timberli/...')
#4 {main}
  thrown in /home/timberli/public_html/ftools/global/code/hooks.php on line 121
[16-Mar-2021 17:51:03 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /home/timberli/public_html/ftools/global/code/hooks.php:121
Stack trace:
#0 /home/timberli/public_html/ftools/global/code/hooks.php(190): ft_get_hook_calls('start', 'code', 'ft_db_connect')
#1 /home/timberli/public_html/ftools/global/code/general.php(31): ft_process_hook_calls('start', Array, Array)
#2 /home/timberli/public_html/ftools/global/library.php(379): ft_db_connect()
#3 /home/timberli/public_html/ftools/process.php(20): require_once('/home/timberli/...')
#4 {main}
  thrown in /home/timberli/public_html/ftools/global/code/hooks.php on line 121
[16-Mar-2021 18:22:51 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /home/timberli/public_html/ftools/global/code/hooks.php:121
Stack trace:
#0 /home/timberli/public_html/ftools/global/code/hooks.php(190): ft_get_hook_calls('start', 'code', 'ft_db_connect')
#1 /home/timberli/public_html/ftools/global/code/general.php(31): ft_process_hook_calls('start', Array, Array)
#2 /home/timberli/public_html/ftools/global/library.php(379): ft_db_connect()
#3 /home/timberli/public_html/ftools/process.php(20): require_once('/home/timberli/...')
#4 {main}
  thrown in /home/timberli/public_html/ftools/global/code/hooks.php on line 121
[16-Mar-2021 18:26:30 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /home/timberli/public_html/ftools/global/code/hooks.php:121
Stack trace:
#0 /home/timberli/public_html/ftools/global/code/hooks.php(190): ft_get_hook_calls('start', 'code', 'ft_db_connect')
#1 /home/timberli/public_html/ftools/global/code/general.php(31): ft_process_hook_calls('start', Array, Array)
#2 /home/timberli/public_html/ftools/global/library.php(379): ft_db_connect()
#3 /home/timberli/public_html/ftools/process.php(20): require_once('/home/timberli/...')
#4 {main}
  thrown in /home/timberli/public_html/ftools/global/code/hooks.php on line 121
[16-Mar-2021 18:28:02 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /home/timberli/public_html/ftools/global/code/hooks.php:121
Stack trace:
#0 /home/timberli/public_html/ftools/global/code/hooks.php(190): ft_get_hook_calls('start', 'code', 'ft_db_connect')
#1 /home/timberli/public_html/ftools/global/code/general.php(31): ft_process_hook_calls('start', Array, Array)
#2 /home/timberli/public_html/ftools/global/library.php(379): ft_db_connect()
#3 /home/timberli/public_html/ftools/process.php(20): require_once('/home/timberli/...')
#4 {main}
  thrown in /home/timberli/public_html/ftools/global/code/hooks.php on line 121
[16-Mar-2021 18:29:12 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /home/timberli/public_html/ftools/global/code/hooks.php:121
Stack trace:
#0 /home/timberli/public_html/ftools/global/code/hooks.php(190): ft_get_hook_calls('start', 'code', 'ft_db_connect')
#1 /home/timberli/public_html/ftools/global/code/general.php(31): ft_process_hook_calls('start', Array, Array)
#2 /home/timberli/public_html/ftools/global/library.php(379): ft_db_connect()
#3 /home/timberli/public_html/ftools/process.php(20): require_once('/home/timberli/...')
#4 {main}
  thrown in /home/timberli/public_html/ftools/global/code/hooks.php on line 121

Thanks Scott
[error_log.txt](https://github.com/formtools/core/files/6151746/error_log.txt)

**Comment by rowright** [comment]
Hey There!

Can you tell me what version of PHP you're using and what version of Form Tools you're using? Based on what I'm seeing I'd first guess that your hosting/server has had an upgrade of your PHP version and the "mysql" package isn't installed. And if you're running an older version of Form Tools, you may not be connecting via PDO (which Form Tools v3 uses instead of that method).

Since you're not able to login to Form Tools - you'll need to get the version number directly from the database.
`select setting_value from {PREFIX}settings where setting_name = 'program_version';`
Where the {PREFIX} is your Form Tools database prefix. You may need to Login to your MySQL server first and validate the Prefix of your tables to find this.

For your PHP version, you'll need to examine your web host / server directly to identify this.

Hope this info helps!

**Comment by resetjet** [comment]
That was exactly it.  I updated form tools and it fixed it.  Thanks for your help.

Scott McGourley
Timberline Lake inc
609-296-7900
Www.timberlinelake.com

**Comment by rowright** [comment]
Hey Scott! 

Glad to hear! If you get a second - feel free to close the issue on GitHub. :)
https://github.com/formtools/core/issues/776

Thanks!
