### ISSUE TITLE
Erro on publishing new form 

### ISSUE THREAD

**Issue by alfeudm** [formtools/core#783]
Fatal error: Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number in D:\xampp\htdocs\FormTools\global\code\Database.class.php:126 Stack trace: #0 D:\xampp\htdocs\FormTools\global\code\Database.class.php(126): PDOStatement->bindValue('form_id', '2', 2) #1 D:\xampp\htdocs\FormTools\global\code\Views.class.php(915): FormTools\Database->bind('form_id', '2') #2 D:\xampp\htdocs\FormTools\modules\form_builder\preview.php(79): FormTools\Views::getFormViews('2') #3 {main} thrown in D:\xampp\htdocs\FormTools\global\code\Database.class.php on line 126

Hy guys, I'm trying to creat simple form with normal fields, like name, phone number and so on. But when i'll try to publish it, I got this error. I'm using xampp control. Anyone has any idea of how can I solve this issue? Thank you in advance.

**Comment by praveenraj2018** [comment]
Yes, it is happend to me as well. The error message is same as you mentioned. Using latest xampp with php 8.0.3 and mysql 8.0.24. Any solution?
