### ISSUE TITLE
Publish this form, Add form using Form Builder and Assigning Forms to Clients are ALL GIVING THE SAME ERROR!

### ISSUE THREAD

**Issue by NiharikaSngh** [formtools/core#858]
`
Fatal error: Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number in C:\xampp\htdocs\formtools\global\code\Database.class.php:126 Stack trace: #0 C:\xampp\htdocs\formtools\global\code\Database.class.php(126): PDOStatement->bindValue('form_id', '13', 2) #1 C:\xampp\htdocs\formtools\global\code\Views.class.php(915): FormTools\Database->bind('form_id', '13') #2 C:\xampp\htdocs\formtools\modules\form_builder\preview.php(79): FormTools\Views::getFormViews('13') #3 {main} thrown in C:\xampp\htdocs\formtools\global\code\Database.class.php on line 126`
### Please provide a solution given that I have not changed any code/file/folder from the form tools zipped folder.

**Comment by nelsondcosta23** [comment]
Hi, 

I see form_id 13, so everything was good and started to gave that error? or was a clean install?
