### ISSUE TITLE
Attempt to remove Orphan records failed 

### ISSUE THREAD

**Issue by HGADerek** [formtools/core#910]
We (HGA) having issues. User view screen colors have reset to default green, and Administrator gets error message when trying to control to custom screen. Ran the FT diagnostic and 22 Orhans foun - but not sure if this is connected.  When "clean-up" orphans is clicked - this is error message.

Fatal error: Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined in /home2/ajdloqb0/public_html/missions/global/code/Database.class.php:126 Stack trace: #0 /home2/ajdloqb0/public_html/missions/global/code/Database.class.php(126): PDOStatement->bindValue('view_id', 29, 1) #1 /home2/ajdloqb0/public_html/missions/global/code/Database.class.php(132): FormTools\Database->bind('view_id', 29) #2 /home2/ajdloqb0/public_html/missions/modules/system_check/code/Orphans.class.php(777): FormTools\Database->bindAll(Array) #3 /home2/ajdloqb0/public_html/missions/modules/system_check/code/Orphans.class.php(65): FormTools\Modules\SystemCheck\Orphans::testEmailTemplateWhenSentViews(true) #4 /home2/ajdloqb0/public_html/missions/modules/system_check/code/Orphans.class.php(151): FormTools\Modules\SystemCheck\Orphans::findTableOrphans('frmtv_email_tem...', true) #5 /home2/ajdloqb0/public_html/missions/modules/system_check/orphans.php(15): FormTools\Modules\SystemCheck\Orphans::cleanOrphans() #6 {main} thrown in /home2/ajdloqb0/public_html/missions/global/code/Database.class.php on line 126

Any ideas or help available to resolve.  Derek - Volunteer - Houston Ground Angels

**Comment by benkeen** [comment]
Hi @HGADerek, sorry for not responding sooner. 

This looks like a PHP 8 bug with the System Check module, but I wouldn't worry too much. The orphan clean up option was just there to make sure there wasn't any clutter left over in your database. It won't cause problems without it running. 

Let me take a look and I'll get back to you.

**Comment by HGADerek** [comment]
Ben – Firstly it is a privilege to be in touch with you directly.  Your Form Tools software was partly configured by a Houston company as a “Public Service’ project for two employees in 2019.  We received it into our On-Line Mission system for medical patients travelling into the Houston Medical Center complex – see www.groundangels.org <http://www.groundangels.org>  

 

You will recognize “ANGEL Sign Up” and “Request and AIR or LOCAL Ride” formats which are our public face.   

 

Houston Ground Angels call me “webmaster” but I have no real IT background, but read the FT documentation, tried to add features and make it more Patient and volunteer driver friendly.  I could (and would like to) show you the awesome use it has been put to – last year we provided around 3900 patient rides.  This year we are up around 30% on ride requests.  I am a driver volunteer and Board member – we have one actual employee who mans ( a lady) the phones and firefights the many daily issues we experience.

 

I would like to show you what we do with your software – and ask you about features I cannot find how to do.  Attempts to engage with smarter people than me have not been fruitful.  Maybe they are simple (not to me) – or not possible.

Your opinion and consultation would be highly beneficial to what we are trying to do.  Please let me know if this is a possibility.

 

Thanks for listening.

 

 

With best regards – Derek King

 

Houston Ground Angels – Volunteer - Board Member & WebMaster

 

Mobile +1 281-923-9634

 ***@***.***> ***@***.***

 

 <http://www.groundangels.org/> www.groundangels.org 

DONATIONS ACCEPTED here -  <https://www.paypal.com/fundraiser/charity/1405456> https://www.paypal.com/fundraiser/charity/1405456

**Comment by benkeen** [comment]
Hey Derek, 

Sure, how about ping me at ben.keen@gmail.com and we can arrange a time to chat? I do want to be upfront though, I have very limited time so I'm not sure how much I'll be able to actually help out. But a chat to talk about what's possible with the software is no problem. :) 

I'm generally free evenings (I'm west coast North America so not too far off your timezone), and sometimes weekends. 

Ben
