### ISSUE TITLE
Deleting field shows PDO error

### ISSUE THREAD

**Issue by benkeen** [formtools/core#911]
> Fatal error: Uncaught PDOException: There is no active transaction in /Applications/MAMP/htdocs/core/dist/global/code/Database.class.php:148 Stack trace: #0 /Applications/MAMP/htdocs/core/dist/global/code/Database.class.php(148): PDO->rollBack() #1 /Applications/MAMP/htdocs/core/dist/global/code/Fields.class.php(1539): FormTools\Database->rollbackTransaction() #2 /Applications/MAMP/htdocs/core/dist/global/code/Fields.class.php(464): FormTools\Fields::deleteFormField('1', '10') #3 /Applications/MAMP/htdocs/core/dist/global/code/Forms.class.php(1571): FormTools\Fields::deleteFormFields('1', Array) #4 /Applications/MAMP/htdocs/core/dist/admin/forms/edit/page_fields.php(21): FormTools\Forms::updateFormFieldsTab('1', Array) #5 /Applications/MAMP/htdocs/core/dist/admin/forms/edit/index.php(122): require_once('/Applications/M...') #6 {main} thrown in /Applications/MAMP/htdocs/core/dist/global/code/Database.class.php on line 148

Seems to delete just fine, however. The page refresh shows the fields are deleted.

**Comment by benkeen** [comment]
Aha!

https://dev.mysql.com/doc/refman/8.0/en/cannot-roll-back.html
